version: 2
updates:
  # Maintain NPM dependencies for the web/Capacitor project
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 10

  # Maintain GitHub Actions within the CI/CD pipeline
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
